version: '3.7'
services:
  nginx:
    container_name: my_nginx
    depends_on:
      - wordpress
    build: #build image from Dockerfile
      context: ./requirements/nginx/
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx #assign the image name
    ports:
      - "443:443"
    restart: unless-stopped #restart container if crashes
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: my_mariadb
    build:
      context: requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_PASSWORD=${DB_PASSWORD}
    image: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: my_wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/
      args:
        - WP_TITLE=${WP_TITLE}
        - WP_DB_HOST=${WP_DB_HOST}
        - WP_ADMIN=${WP_ADMIN}
        - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_USER=${WP_USER}
        - WP_USER_PASSWORD=${WP_USER_PASSWORD}
        - WP_USER_EMAIL=${WP_USER_EMAIL}
    image: wordpress
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

volumes:
  wordpress:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/denizozd/Documents/inception/wordpress
      o: bind

  mariadb:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/denizozd/Documents/inception/mariadb
      o: bind

networks:
  inception:
    driver: bridge #change to default?
