version: '3.7'
services:
    nginx:
      container_name: my_nginx
      build:
        context: ./requirements/nginx/
      ports:
        - "443:443"
        - "8080:8080"
      expose:
        - "9000"
      environment:
        PASSWORD: "${PASSWORD}"
